yarnPath: .yarn/releases/yarn-rc.js
nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com
npmRegistries:
  //npm.fontawesome.com:
    npmAlwaysAuth: true
    # See: https://fontawesome.com/account
    # npmAuthToken:
